package furhatos.app.courseadvisor.api

enum class Department(
    val code: String,
    val displayName: String
) {
    A("A", "All within Architecture and the Built Environment"),
    AIJ("AIJ", "Surveying – Geodesy, Land Law and Real Estate Planning"),
    ADB("ADB", "Architecture"),
    ADC("ADC", "Architecture"),
    ADD("ADD", "Architecture"),
    ADI("ADI", "Architecture, Culture and Environment"),
    ADJ("ADJ", "Architecture, Landscapes and Cities"),
    ADH("ADH", "Architecture, Technique and Theory"),
    AFB("AFB", "Building Materials"),
    AF("AF", "Civil and Architectural Engineering"),
    AFA("AFA", "Civil and Architectural Engineering"),
    AFF("AFF", "Concrete Structures"),
    AID("AID", "Construction and Facilities Management"),
    AFK("AFK", "Constructional Engineering and Design"),
    AMB("AMB", "Contract Education: Urban Development and Design"),
    AFV("AFV", "Division of Road and Railway Engineering"),
    AGF("AGF", "Geoinformatics"),
    AKC("AKC", "History of Science, Technology and Environment"),
    ADF("ADF", "Lighting Design"),
    AKB("AKB", "Philosophy"),
    AIE("AIE", "Real Estate Business and Financial Systems"),
    AIB("AIB", "Real Estate Economics and Finance"),
    ALK("ALK", "Resources, Energy and Infrastructure"),
    AAB("AAB", "School of Architecture and the Built Environment"),
    AFH("AFH", "Soil- and Rock Mechanics"),
    ALH("ALH", "Strategic Sustainability Studies"),
    AFE("AFE", "Structural Design & Bridges"),
    ALF("ALF", "Sustainability and Environmental Engineering"),
    ALG("ALG", "Sustainability Assessment and Management"),
    AFT("AFT", "Sustainable Buildings"),
    AL("AL", "Sustainable development, environmental science and engineering"),
    AGI("AGI", "Transport and Systems Analysis"),
    AFP("AFP", "Transport Planning"),
    AGB("AGB", "Urban and Regional Studies"),
    ALI("ALI", "Water and Environmental Engineering"),

    B("B", "All within Biotechnology"),
    BA("BA", "Biotechnology"),
    BB("BB", "Biotechnology"),

    C("C", "All within Engineering Sciences in Chemistry, Biotechnology and Health"),
    CD("CD", "Biomedical Engineering and Health Systems"),
    CF("CF", "Chemical Engineering"),
    CE("CE", "Chemistry"),
    CM("CM", "Engineering Pedagogics"),
    CG("CG", "Fibre and Polymer Technology"),
    CH("CH", "Gene Technology"),
    CK("CK", "Industrial Biotechnology"),
    CJ("CJ", "Protein Science"),
    CB("CB", "School-wide"),
    CL("CL", "Theoretical Chemistry and Biology"),

    J("J", "All within Electrical Engineering and Computer Science"),
    JHF("JHF", "Communication Systems"),
    JHS("JHS", "Computational Science and  Technology"),
    JH("JH", "Computer Science"),
    JRL("JRL", "Decision and Control Systems"),
    JJN("JJN", "Electric Power and Energy Systems"),
    JJ("JJ", "Electrical Engineering"),
    JJI("JJI", "Electromagnetic Engineering"),
    JJG("JJG", "Electronics and Embedded Systems"),
    JJD("JJD", "Fusion Plasma Physics"),
    JM("JM", "Human Centered Technology"),
    JRO("JRO", "Information Science and Engineering"),
    JR("JR", "Intelligent Systems"),
    JMA("JMA", "Media Technology and Interaction Design"),
    JRQ("JRQ", "Micro and Nano Systems"),
    JHP("JHP", "Network and Systems Engineering"),
    JRR("JRR", "Robotics, Perception and Learning"),
    JHK("JHK", "Software and Computer Systems"),
    JJE("JJE", "Space and Plasma Physics"),
    JRT("JRT", "Speech, Music and Hearing"),
    JHT("JHT", "Theoretical Computer Science"),

    M("M", "All within Industrial Engineering and Management"),
    MJEB("MJEB", "Applied Thermodynamics and Refrigeration"),
    MI("MI", "Casting of metals"),
    MJEM("MJEM", "Energy Systems"),
    MD("MD", "Energy Technology"),
    MJ("MJ", "Energy Technology"),
    MJEA("MJEA", "Energy Technology"),
    MJEC("MJEC", "Heat and Power Technology"),
    ME("ME", "Industrial Economics and Management"),
    MFG("MFG", "Integrated Product Development and Design"),
    MFGG("MFGG", "Integrated Product Development and Design"),
    MO("MO", "Learning in Engineering Sciences"),
    MF("MF", "Machine Design"),
    MH("MH", "Materials Science and Engineering"),
    MV("MV", "Materials Science and Engineering"),
    MFC("MFC", "Mechatronics"),
    ML("ML", "Production Engineering"),
    MLH("MLH", "Production Engineering Södertälje"),
    MLG("MLG", "Production Engineering Stockholm"),
    MAC("MAC", "School of Industrial Engineering and Management"),
    MFEE("MFEE", "SKD GRU"),

    S("S", "All within Engineerings Sciences"),
    SD("SD", "Aeronautical and Vehicle Engineering"),
    SK("SK", "Applied Physics"),
    SKB("SKB", "Applied undergraduate Physics"),
    SM("SM", "Engineering Mechanics"),
    SA("SA", "Engineering Sciences"),
    SF("SF", "Mathematics"),
    SG("SG", "Mechanics"),
    SH("SH", "Physics"),
    SE("SE", "Solid Mechanics"),
    SI("SI", "Theoretical Physics"),
    SIB("SIB", "Theoretical Undergaduate Physics"),
    SHB("SHB", "Undergraduate Physics"),

    U("U", "All within Externa lärosäten"),
    UL("UL", "Stockholms universitet"),

    D("D", "All within Computer Science and Communication"),
    DM("DM", "Media Technology and Interaction Design"),

    H("H", "All within Technology and Health"),
    HPN("HPN", "Ergonomics"),
    HA("HA", "Technology and Health"),

    K("K", "All within Chemical Science and Engineering"),
    KE("KE", "Chemical Engineering and Technology"),
    KD("KD", "Chemistry"),
    KF("KF", "Fibre and Polymer Technology"),

    L("L", "All within Education and Communication"),
    LA("LA", "Education and Communication in Engineering Science"),
    LPA("LPA", "Teacher Education");

    companion object {
        private val nameIndex = values().associateBy { it.displayName.lowercase() }

        fun fromName(name: String): Department? =
            nameIndex[name.lowercase()]
    }
}